### PR TITLE
Build for g++-4.9

### PR DESCRIPTION
**Pull request by brunoabinader**
Adds support for compiling geometry.hpp tests - thus also working as a valid use case - in GCC 4.9. Unfortunately, there are some bugs in GCC 4.9 that we have to accommodate.

### CODE REVIEW

**Comment by brunoabinader** [comment]
@artemp sorry I didn't notice that https://github.com/mapbox/geometry.hpp/pull/48 was up - want to merge those patches here?

File: include/mapbox/geometry/point_arithmetic.hpp [hunk 1]
```diff
@@ -4,111 +4,111 @@ namespace mapbox {
 namespace geometry {
 
 template <typename T>
-constexpr point<T> operator+(point<T> const& lhs, point<T> const& rhs)
+  point<T> operator+(point<T> const& lhs, point<T> const& rhs)
```
Comment (jfirebaugh) [inline include/mapbox/geometry/point_arithmetic.hpp]: Nit: remove the leading spaces.

File: tests/test.cpp [hunk 2]
```diff
@@ -129,7 +129,12 @@ static void testGeometryCollection() {
 }
 
 static void testFeature() {
+#if !defined(__GNUC__) || __GNUC__ >= 5
     feature<double> pf { point<double>() };
```
Comment (jfirebaugh) [inline tests/test.cpp]: Does g++4.9 have an issue with this line? What's the error?

File: include/mapbox/geometry/geometry.hpp [hunk 3]
```diff
@@ -37,7 +37,9 @@ struct geometry : geometry_base<T>
      * The default constructor would create a point geometry with default-constructed coordinates;
      * i.e. (0, 0). Since this is not particularly useful, and could hide bugs, it is disabled.
      */
+#if !defined(__GNUC__) || __GNUC__ >= 5
```
Comment (jfirebaugh) [inline include/mapbox/geometry/geometry.hpp]: Can you add a comment explaining the reason for this macro?

File: tests/test.cpp (hunk 2 above)
Comment (tmpsantos) [inline tests/test.cpp]: g++ only supports aggregates with non-static data member initializers from 5.0:

https://gcc.gnu.org/gcc-5/changes.html

```
G++ now supports C++14 aggregates with non-static data member initializers.
struct A { int i, j = i; };
A a = { 42 }; // a.j is also 42
```

Comment (jfirebaugh) [inline tests/test.cpp]: 👍 Let's avoid the macros by adding a constructor to `feature` with default arguments for `properties` and `id`.

File: include/mapbox/geometry/geometry.hpp (hunk 3 above)
Comment (brunoabinader) [inline include/mapbox/geometry/geometry.hpp]: Same as above - let's try the extra constructor approach :+1:

File: include/mapbox/geometry/feature.hpp [hunk 4]
```diff
@@ -55,6 +55,10 @@ struct feature
     geometry_type geometry;
     property_map properties {};
     std::experimental::optional<identifier> id {};
+
+    // GCC 4.9 does not support C++14 aggregates with non-static data member
+    // initializers.
+    feature(geometry_type const& geometry_) : geometry(geometry_) {}
```
Comment (jfirebaugh) [inline include/mapbox/geometry/feature.hpp]: How about:

```
feature(geometry_type geometry_,
        property_map properties_,
        std::experimental::optional<identifier> id_)
    : geometry(std::move(geometry_)),
      properties(std::move(properties_)),
      id(std::move(id_)) {}
```

Then all compilers can initialize with 1, 2, or 3 arguments, and `modernize-pass-by-value` is happy.

Comment (brunoabinader) [inline include/mapbox/geometry/feature.hpp]: This works in GCC 4.9 :+1: :
```
feature(geometry_type geometry_,
        property_map properties_ = property_map {},
        std::experimental::optional<identifier> id_ = std::experimental::optional<identifier> {})
    : geometry(std::move(geometry_)),
      properties(std::move(properties_)),
      id(std::move(id_)) {}
```

We have to be explicit when using the bracket initialization otherwise compilation fails with the following output:
> tests/test.cpp:132:42: error: converting to ‘mapbox::geometry::property_map {aka std::unordered_map<std::basic_string<char>, mapbox::geometry::value>}’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = mapbox::geometry::value; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_string<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, mapbox::geometry::value> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, mapbox::geometry::value> >]’
